<?php
require_once '../includes/config.php';
require_once '../includes/accounting_helper.php';
require_once '../includes/cashbox_helper.php';
accountingEnsureSchema($pdo); cashboxEnsureSchema($pdo); cashboxEnsureProviderColumn($pdo);
requireStaffOrAdmin($pdo, 'perm_accounting_view');
$canEdit=isAdmin() || canAccess($pdo,'perm_accounting_edit');
if($_SERVER['REQUEST_METHOD']==='POST') adminCsrfVerify();
$pageTitle='يومية الصناديق — '.SITE_NAME;
$flash=null;

if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['save_movement'])){
    if(!$canEdit){flashMessage('danger','ليس لديك صلاحية تسجيل حركات الصناديق'); redirect(SITE_URL.'/admin/accounting_cashbox_movements.php');}
    try{
        $type=(string)($_POST['movement_type']??''); $boxId=(int)($_POST['cashbox_id']??0); $amount=(float)($_POST['amount']??0);
        $date=(string)($_POST['entry_date']??date('Y-m-d')); $desc=trim((string)($_POST['description']??''));
        if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)) throw new InvalidArgumentException('تاريخ الحركة غير صالح');
        if(in_array($type,['receipt','payment','opening'],true)){
            cashboxCreateMovement($pdo,[
                'cashbox_id'=>$boxId,'movement_type'=>$type,'amount'=>$amount,'description'=>$desc,'entry_date'=>$date,
                'counterpart_account_id'=>(int)($_POST['counterpart_account_id']??0),'reference_type'=>trim((string)($_POST['reference_type']??'')) ?: 'cashbox_movement',
                'reference_id'=>trim((string)($_POST['reference_id']??'')) ?: null,'staff_id'=>(int)($_POST['staff_id']??0) ?: null,
                'created_by'=>(int)($_SESSION['user_id']??0) ?: null,'idempotency_key'=>trim((string)($_POST['idempotency_key']??'')) ?: null,
            ]);
            logStaffAction($pdo,$type==='receipt'?'قبض من صندوق':($type==='payment'?'صرف من صندوق':'رصيد افتتاحي لصندوق'),'cashbox',$boxId,$desc);
        } elseif($type==='transfer_in') {
            $result=cashboxTransfer($pdo,(int)($_POST['from_cashbox_id']??0),$boxId,$amount,$desc,$date,(int)($_SESSION['user_id']??0) ?: null);
            logStaffAction($pdo,'تحويل بين صندوقين','cashbox',$result['in_id'],$desc);
        } else throw new InvalidArgumentException('اختر نوع حركة صحيحاً');
        flashMessage('success','تم تسجيل الحركة وترحيل القيد عند اكتمال طرفيه');
        redirect(SITE_URL.'/admin/accounting_cashbox_movements.php?cashbox_id='.$boxId);
    }catch(Throwable $e){$flash=['type'=>'danger','message'=>$e->getMessage()];}
}

$cashboxes=$pdo->query("SELECT c.*,u.username staff_username,u.full_name staff_name,a.code account_code,a.name account_name FROM accounting_cashboxes c LEFT JOIN users u ON u.id=c.staff_id LEFT JOIN accounting_accounts a ON a.id=c.account_id ORDER BY c.status='active' DESC,c.name")->fetchAll(PDO::FETCH_ASSOC);
$accounts=$pdo->query("SELECT id,code,name,currency_code FROM accounting_accounts WHERE status=1 ORDER BY code")->fetchAll(PDO::FETCH_ASSOC);
$selectedId=(int)($_GET['cashbox_id']??0); if(!$selectedId && $cashboxes) $selectedId=(int)$cashboxes[0]['id'];
$from=(string)($_GET['from']??date('Y-m-01')); $to=(string)($_GET['to']??date('Y-m-d'));
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from))$from=date('Y-m-01'); if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to))$to=date('Y-m-d');
$selected=null; foreach($cashboxes as $c){if((int)$c['id']===$selectedId){$selected=$c;break;}}
$opening=0.0;$closing=0.0;$rows=[];$summary=['receipt'=>0.0,'payment'=>0.0,'transfer_in'=>0.0,'transfer_out'=>0.0,'opening'=>0.0];
if($selected){
    $opening=cashboxBalance($pdo,$selectedId,date('Y-m-d',strtotime($from.' -1 day')));
    $st=$pdo->prepare("SELECT m.*,c.name cashbox_name,cc.name counterpart_name,u.username staff_username,u.full_name staff_name,j.id journal_exists FROM accounting_cashbox_movements m JOIN accounting_cashboxes c ON c.id=m.cashbox_id LEFT JOIN accounting_cashboxes cc ON cc.id=m.counterpart_cashbox_id LEFT JOIN users u ON u.id=m.staff_id LEFT JOIN accounting_journal j ON j.id=m.journal_id WHERE m.cashbox_id=? AND m.entry_date BETWEEN ? AND ? ORDER BY m.entry_date,m.id");
    $st->execute([$selectedId,$from,$to]); $rows=$st->fetchAll(PDO::FETCH_ASSOC);
    $running=$opening; foreach($rows as &$r){$r['signed_amount']=cashboxMovementSign($r['movement_type'])*(float)$r['amount'];$running+=(float)$r['signed_amount'];$summary[$r['movement_type']]+=(float)$r['amount'];$r['running_balance']=$running;} unset($r); $closing=$running;
}
$flash=$flash?:getFlash(); include 'header.php';
?>
<style>
.cm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.cm-grid .full{grid-column:1/-1}.cm-table{min-width:1120px}.cm-table td,.cm-table th{white-space:nowrap}.cm-muted{color:var(--text3);font-size:.82rem}.cm-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.cm-kpi{background:rgba(255,255,255,.03);border:1px solid var(--border);border-radius:12px;padding:13px}.cm-kpi span{display:block;color:var(--text3);font-size:.78rem}.cm-kpi b{display:block;margin-top:5px;font-size:1.05rem}.cm-in{color:#00d4aa}.cm-out{color:#ff8f9d}@media(max-width:850px){.cm-grid,.cm-kpis{grid-template-columns:1fr 1fr}}@media(max-width:560px){.cm-grid,.cm-kpis{grid-template-columns:1fr}}
</style>
<?php if($flash): ?><div class="alert alert-<?=htmlspecialchars($flash['type'])?>"><?=htmlspecialchars($flash['message'])?></div><?php endif; ?>
<div class="page-header"><div><h2><i class="fas fa-book" style="color:var(--cyan)"></i> يومية الصناديق</h2><p>القبض والصرف والتحويلات المرحّلة فقط، مع رصيد افتتاحي وختامي للفترة.</p></div><div><a href="accounting_cashboxes.php" class="btn btn-secondary"><i class="fas fa-cash-register"></i> إدارة الصناديق</a></div></div>
<?php if($canEdit): ?><div class="card"><div class="card-body"><h3 style="margin-top:0"><i class="fas fa-plus-circle"></i> تسجيل حركة</h3><form method="post"><input type="hidden" name="save_movement" value="1"><?=adminCsrfField()?><div class="cm-grid"><div class="form-group"><label>نوع الحركة</label><select name="movement_type" id="movement_type"><option value="receipt">قبض</option><option value="payment">صرف</option><option value="opening">رصيد افتتاحي</option><option value="transfer_in">تحويل من صندوق إلى صندوق</option></select></div><div class="form-group"><label>الصندوق المستفيد / المنفذ</label><select name="cashbox_id" id="cashbox_id" required><?php foreach($cashboxes as $c): ?><option value="<?=$c['id']?>" <?=((int)$c['id']===$selectedId)?'selected':''?>><?=htmlspecialchars($c['name'].' — '.$c['code'].' ('.$c['currency_code'].')')?></option><?php endforeach; ?></select></div><div class="form-group" id="from_box_group" style="display:none"><label>الصندوق المصدر</label><select name="from_cashbox_id"><?php foreach($cashboxes as $c): ?><option value="<?=$c['id']?>"><?=htmlspecialchars($c['name'].' — '.$c['code'])?></option><?php endforeach; ?></select></div><div class="form-group"><label>المبلغ</label><input type="number" name="amount" min="0.00000001" step="0.00000001" required></div><div class="form-group" id="counterpart_group"><label>الحساب المقابل</label><select name="counterpart_account_id"><option value="">اختر الحساب المقابل</option><?php foreach($accounts as $a): ?><option value="<?=$a['id']?>"><?=htmlspecialchars($a['code'].' — '.$a['name'].' ('.$a['currency_code'].')')?></option><?php endforeach; ?></select><small class="cm-muted">مطلوب للقبض والصرف حتى يكون القيد ثنائي الطرف، ولا يلزم للرصيد الافتتاحي.</small></div><div class="form-group"><label>تاريخ الحركة</label><input type="date" name="entry_date" value="<?=htmlspecialchars($to)?>" required></div><div class="form-group"><label>نوع المرجع</label><input name="reference_type" placeholder="order / provider / manual"></div><div class="form-group"><label>رقم المرجع</label><input name="reference_id" placeholder="ID... أو رقم سند"></div><div class="form-group full"><label>البيان</label><textarea name="description" rows="2" required placeholder="سبب القبض أو الصرف أو التحويل ومصدره الفعلي"></textarea></div><div class="form-group"><label>مفتاح منع التكرار، اختياري</label><input name="idempotency_key" maxlength="190" placeholder="مرجع فريد من المصدر"></div></div><div style="margin-top:15px"><button class="btn btn-primary"><i class="fas fa-save"></i> تسجيل وترحيل</button></div></form></div></div><?php endif; ?>
<div class="card"><div class="card-body"><form method="get" style="display:flex;gap:8px;align-items:end;flex-wrap:wrap"><div class="form-group" style="min-width:240px;margin:0"><label>الصندوق</label><select name="cashbox_id"><?php foreach($cashboxes as $c): ?><option value="<?=$c['id']?>" <?=((int)$c['id']===$selectedId)?'selected':''?>><?=htmlspecialchars($c['name'].' — '.$c['code'])?></option><?php endforeach; ?></select></div><div class="form-group" style="margin:0"><label>من</label><input type="date" name="from" value="<?=htmlspecialchars($from)?>"></div><div class="form-group" style="margin:0"><label>إلى</label><input type="date" name="to" value="<?=htmlspecialchars($to)?>"></div><button class="btn btn-secondary"><i class="fas fa-filter"></i> عرض اليومية</button></form></div></div>
<?php if($selected): ?><div class="card"><div class="card-body"><div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><div><h3 style="margin:0"><?=htmlspecialchars($selected['name'])?> <span class="cm-muted">(<?=htmlspecialchars($selected['code'])?>)</span></h3><div class="cm-muted">الموظف: <?=htmlspecialchars($selected['staff_name']?:$selected['staff_username']?:'—')?> — الحساب: <?=htmlspecialchars(($selected['account_code']?$selected['account_code'].' — ':'').($selected['account_name']?:'غير مربوط'))?></div></div><div class="cm-muted">الفترة: <?=htmlspecialchars($from)?> إلى <?=htmlspecialchars($to)?></div></div><div class="cm-kpis"><div class="cm-kpi"><span>الرصيد الافتتاحي</span><b><?=number_format($opening,8,'.',',')?> <?=htmlspecialchars($selected['currency_code'])?></b></div><div class="cm-kpi"><span>إجمالي القبض والتحويل الوارد</span><b class="cm-in"><?=number_format($summary['receipt']+$summary['transfer_in'],8,'.',',')?></b></div><div class="cm-kpi"><span>إجمالي الصرف والتحويل الصادر</span><b class="cm-out"><?=number_format($summary['payment']+$summary['transfer_out'],8,'.',',')?></b></div><div class="cm-kpi"><span>الرصيد الختامي الفعلي</span><b><?=number_format($closing,8,'.',',')?> <?=htmlspecialchars($selected['currency_code'])?></b></div></div><div class="table-wrap"><table class="cm-table"><thead><tr><th>التاريخ</th><th>نوع الحركة</th><th>المبلغ</th><th>الصندوق المقابل</th><th>المرجع</th><th>البيان</th><th>الموظف</th><th>القيد</th><th>الرصيد بعد الحركة</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=htmlspecialchars($r['entry_date'])?></td><td><?=htmlspecialchars(cashboxTypeLabel($r['movement_type']))?></td><td class="<?=cashboxMovementSign($r['movement_type'])>0?'cm-in':'cm-out'?>"><?=cashboxMovementSign($r['movement_type'])>0?'+':'-'?><?=number_format((float)$r['amount'],8,'.',',')?></td><td><?=htmlspecialchars($r['counterpart_name']?:'—')?></td><td><?=htmlspecialchars(($r['reference_type']?:'').' '.($r['reference_id']?:''))?></td><td><?=htmlspecialchars($r['description'])?></td><td><?=htmlspecialchars($r['staff_name']?:$r['staff_username']?:'—')?></td><td><?=$r['journal_exists']?'<span class="cm-in">مرحل #'.(int)$r['journal_exists'].'</span>':'<span class="cm-muted">افتتاحي/غير مرحل</span>'?></td><td><?=number_format((float)$r['running_balance'],8,'.',',')?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="9" style="text-align:center;padding:30px;color:var(--text3)">لا توجد حركات فعلية في الفترة المحددة</td></tr><?php endif; ?></tbody></table></div></div></div><?php endif; ?>
<script>document.getElementById('movement_type')?.addEventListener('change',function(){const t=this.value;document.getElementById('from_box_group').style.display=t==='transfer_in'?'block':'none';document.getElementById('counterpart_group').style.display=(t==='transfer_in'||t==='opening')?'none':'block';});</script>
<?php include 'footer.php'; ?>
